Refactor/add UUID to all model
charkchalk/backend pull request #22
Opened 2023-03-01 17:26 UTC by YukinaMochizuki

## Refactor
- add uuid field to
  - tags
  - date range
  - organization

2023-03-01 18:02 UTC, moontai0724 requested changes
Some advice may needs review

2023-03-01 18:02 UTC, moontai0724 commented on src/main/java/io/charkchalk/backend/entity/Place.java
> +    private UUID uuid;
Seems like missing `@GeneratedValue(strategy = GenerationType.AUTO)` here?

2023-03-01 18:02 UTC, moontai0724 commented on src/main/java/io/charkchalk/backend/service/range/date/DateController.java
>      }
May we have data that returned by `dateRangeRepository.save(dateRange);`? I am worry about further usage without UUID returned type `BaseDateRangeJson` instead of `DateRangeJson`.

2023-03-01 18:02 UTC, moontai0724 commented on src/main/java/io/charkchalk/backend/service/tag/TagController.java
>      }
Same issue about base type and full type above. May be better if we have UUID after created an item.

2023-03-01 18:02 UTC, moontai0724 commented on src/main/java/io/charkchalk/backend/service/range/date/DateController.java
> +    public ResponseEntity<BaseDateRangeJson> putDateRange(@PathVariable @NotNull UUID uuid,
May be better if keep consistency of return type with other methods?

2023-04-02 07:02 UTC, YukinaMochizuki commented on src/main/java/io/charkchalk/backend/entity/Place.java
> +    private UUID uuid;
yes, you are right

2023-04-02 15:06 UTC, moontai0724 approved these changes

2023-04-02 15:06 UTC, merged